---
# tasks file for ansible-postgis3d
- name: Creating the build directory
  file: path={{ build_directory }} state=directory

- apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
           state=present
           id=ACCC4CF8
  become: yes

- name: Configure the PostgreSQL APT repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main"
                  state=present
  become: yes

- name: Installing dependencies
  action: apt pkg={{ item }} state=present update_cache=yes
  become: yes
  with_items:
    - postgresql-9.4
    - postgresql-server-dev-9.4
    - build-essential
    - autoconf
    - cmake
    - docbook-mathml
    - docbook-xsl
    - libboost-dev
    - libboost-thread-dev
    - libboost-filesystem-dev
    - libboost-timer-dev
    - libboost-iostreams-dev
    - libboost-program-options-dev
    - libcunit1-dev
    - libgdal-dev
    - libgeos++-dev
    - libgeotiff-dev
    - libgmp-dev
    - libjson0-dev
    - libjson-c-dev
    - liblas-dev
    - libmpfr-dev
    - libopenscenegraph-dev
    - libpq-dev
    - libproj-dev
    - libxml2-dev
    - xsltproc
    - xz-utils

###### CGAL

- name: Install CGAL from packages
  apt: pkg=libcgal-dev
  when: ansible_distribution_release != "trusty"
  become: yes

- name: Get CGAL source code
  get_url: url=https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.6.3/CGAL-4.6.3.tar.xz
           dest={{ build_directory }}
  when: ansible_distribution_release == "trusty"

- shell: tar -Jxf CGAL-4.6.3.tar.xz
        chdir={{ build_directory}}
        creates={{ build_directory}}/CGAL-4.6.3
  when: ansible_distribution_release == "trusty"

- shell: cmake . && make -j{{ ansible_processor_cores }}
         chdir={{ build_directory }}/CGAL-4.6.3
  when: ansible_distribution_release == "trusty"

- shell: make install
         chdir={{ build_directory }}/CGAL-4.6.3
  become: yes
  when: ansible_distribution_release == "trusty"


###### SFCGAL

- name: get sfcgal code
  get_url: url=https://github.com/Oslandia/SFCGAL/archive/v{{ sfcgal_version }}.tar.gz
           dest={{ build_directory }}/sfcgal.tar.gz

- shell: tar -xzf sfcgal.tar.gz
         chdir={{ build_directory}}
         creates={{ build_directory}}/SFCGAL-{{ sfcgal_version }}

- shell: cmake . && make -j{{ ansible_processor_cores }}
         chdir={{ build_directory }}/SFCGAL-{{ sfcgal_version }}

- shell: make install
         chdir={{ build_directory }}/SFCGAL-{{ sfcgal_version }}
  become: yes

###### POSTGIS


- get_url: url=http://download.osgeo.org/postgis/source/postgis-{{ postgis_version }}.tar.gz
            dest={{ build_directory }}/

- shell: tar -xzf postgis-{{ postgis_version }}.tar.gz
         chdir={{ build_directory }}
         creates={{ build_directory}}/postgis-{{ postgis_version }}

- shell: ./configure && make
         chdir={{ build_directory }}/postgis-{{ postgis_version }}/

- shell: make install
         chdir={{ build_directory }}/postgis-{{ postgis_version }}/
  become: yes


###### POINTCLOUD

- get_url: url=https://github.com/pgpointcloud/pointcloud/archive/v{{ pointcloud_version }}.tar.gz
           dest={{ build_directory }}/

- shell: tar -xvf pointcloud-{{ pointcloud_version }}.tar.gz
         chdir={{ build_directory }}
         creates={{ build_directory}}/pointcloud-{{ pointcloud_version }}

- shell: ./autogen.sh && ./configure && make -j{{ ansible_processor_cores }}
         chdir={{ build_directory }}/pointcloud-{{ pointcloud_version }}

- shell: make install
         chdir={{ build_directory }}/pointcloud-{{ pointcloud_version }}
  become: yes

###### PDAL

- get_url: url=https://github.com/PDAL/PDAL/archive/{{ pdal_version }}.tar.gz
           dest={{ build_directory }}/

- shell: tar -xvf PDAL-{{ pdal_version }}.tar.gz
         chdir={{ build_directory }}

- shell: cmake . && make -j{{ ansible_processor_cores }}
         chdir={{ build_directory }}/PDAL-{{ pdal_version }}

- shell: make install
         chdir={{ build_directory }}/PDAL-{{ pdal_version }}
  become: yes
